- Check internet connectivity via MQTT before backup (experimental, still in progress) - Move GNOME files and rules to a dedicated directory for modularization (experimental, still in progress) - Add initial setup target for specialized/non-common tasks - Update dotfiles for Fedora 43 and fix broken dependencies - Optimize DNF calls by adding redundant check logic - Move `sensors-detect` to the `setup` phase to handle user input - Create a "fake" user `network-online.target` to fix backup services and timers (experimental, still in progress) - Update initial installation steps in README.md

diff --git a/fsroot/home/obatiuk/.home/bin/restic-backup b/fsroot/home/obatiuk/.home/bin/restic-backup
--- a/fsroot/home/obatiuk/.home/bin/restic-backup
+++ b/fsroot/home/obatiuk/.home/bin/restic-backup
@@ -162,6 +162,15 @@ done
 
 # --- Main Execution Block ---
 
+# Check that internet is online
+_internet_status=$(mosquitto_sub ${MQTT_PUB_ARGS} -N -t "home/internet/primary/state" -C 1 -W 2 2>/dev/null || true)
+if [ "${_internet_status}" != "online" ]; then
+	echo "Primary internet is offline. Aborting!"
+	mosquitto_pub ${MQTT_PUB_ARGS} -r -t "${HASS_BACKUP_STATE_TOPIC}" -m "{\"state\" : \"Failure\"}" || true
+	_notify "critical" "Primary internet connection is offline. Aborting!" > /dev/null || true
+	exit 1;
+fi
+
 # Configure repository device using MQTT autodiscovery feature in Home Assistant
 # echo "Following restic repository MQTT payload will be used for autodiscovery:"
 # echo "${HASS_RESTIC_REPOSITORY_DISCOVERY_PAYLOAD}" | jq
